### ISSUE TITLE
GetNextEntry

### ISSUE THREAD

**Issue by alonmat** [icsharpcode/SharpZipLib#107]
On portable version:

sometimes I need to scan the ZipInputStream twice. so it will be great if
I will have GetFirstEntry (in addition to GetNextEntry)

**Comment by McNeight** [comment]
@alonmat 

The package you are using is currently a fork of SharpZipLib by @ygrenier at https://github.com/ygrenier/SharpZipLib.Portable

At the moment I am focused more on cleaning up the existing code and bug fixing, rather than adding new features. Hopefully soon, we can take a look at incorporating those features into our project.

-Neil

**Comment by Numpsy** [comment]
Would that give you anything over just creating two input streams or using ZipFile?

**Comment by piksel** [comment]
Yeah, this does seem both specialized and easy to resolve using the consumers own code. I'll close this since it hasn't been touched in 4 years.
