### ISSUE TITLE
SharpZipLib 0.84 can not open archives created with latest version

### ISSUE THREAD

**Issue by gabisandor** [icsharpcode/SharpZipLib#131]
### Steps to reproduce
1. Create a ZIP file using the latest version of the library.
2. Try to open the ZIP file with an older version of the library, e.g. 0.84.

### Expected behavior
The ZIP file should be successfully open by the old version of the library.

### Actual behavior
An exception is thrown by the old library:

Version required to extract this entry not supported (45)

at ICSharpCode.SharpZipLib.Zip.ZipFile.TestLocalHeader(ZipEntry entry, Boolean fullTest, Boolean extractTest)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.CheckLocalHeader(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(Int32 entryIndex)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)

### Workaround

Set UseZip64 property to false on ZipOutputStream:

zipOutputStream.UseZip64 = UseZip64.Off;

### Obtained from (place an x between the brackets for all that apply)
- [x] Compiled from source
 - branch: master
 - commit: 00c3c91
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by McNeight** [comment]
@gabisandor 
It would appear that this "incompatibility" is intentional. Here is a brief timeline from the Changes.txt file and git history:
* Version 0.84 does not have the capability to handle Zip64 extensions
* Version 0.85.0.0 `Add support for Zip64 handling to both streams and ZipFile classes.`
* Versions up to 0.85.1.268 created files by default with `UseZip64 useZip64_ = UseZip64.Dynamic;`
* Version 0.85.1.269 c38c6f4b1bbfe3ebc1d7b95c301286355449b400 changes ZipOutputStream.cs to
```CSharp
// Default of off is backwards compatible and doesnt dump on
// XP's built in compression which cnat handle it
UseZip64 useZip64_ = UseZip64.Off;
``` 
* Version 0.85.1.271 `Zip64 handling altered to default to "Zip32" for compatability.`
* Version 0.85.4.365 1cdcdf5b9c246193b06fa0fd66543f7b911420e8 changes ZipOutputStream.cs to
```CSharp
/// <remarks>Older archivers may not understand Zip64 extensions.
/// If backwards compatability is an issue be careful when adding <see cref="ZipEntry.Size">entries</see> to an archive.
/// Setting this property to off is workable but less desirable as in those circumstances adding a file
/// larger then 4GB will fail.</remarks>
```
and
```CSharp
// Default is dynamic which is not backwards compatible and can cause problems
// with XP's built in compression which cant read Zip64 archives.
// However it does avoid the situation were a large file is added and cannot be completed correctly.
// NOTE: Setting the size for entries before they are added is the best solution!
UseZip64 useZip64_ = UseZip64.Dynamic;
```
* Version 0.85.4.369 "ZipFile now defaults to dynamic use of Zip64."

Your workaround is the correct solution for this issue.

-Neil

**Comment by gabisandor** [comment]
Thank you very much @McNeight for your detailed insight into this issue. I will then stick to setting Zip64 to off from now on when i need backwards compatibility. From what I understood, the only problem will come up if i try to zip a file that is larger than 4 GB.
