### ISSUE TITLE
ZipFile(Stream) constructor closes the stream before user can set IsStreamOwner

### ISSUE THREAD

**Issue by jaymrobinson** [icsharpcode/SharpZipLib#144]
### Steps to reproduce
1. Pass a stream containing a .pdf file to the ZipFile(Stream) constructor
2. Catch exception (ZipException: Cannot find central directory)
3. Attempt to access the stream again
### Expected behavior

The constructor shouldn't automatically close the stream on an exception.
At least, there should be an optional constructor parameter to specify IsStreamOwner.
### Actual behavior

The constructor closes the stream, so we can't do anything with it after the constructor fails.
### Version of SharpZipLib

0.86.0.518
### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
  - branch: _______
  - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
  - [ x] NuGet
  - [ ] MyGet
  - [ ] Chocolatey

**Comment by Numpsy** [comment]
Hi,

I fell over this while doing some tests with the library, and thought i'd have a look at it.

Would something like https://github.com/Numpsy/SharpZipLib/commit/f1dddff99d5cdf97d0174847c5a425430ed5f29f be acceptable? (that avoids the issue in my use case).

I called the parameter 'leaveOpen' because that's what some other .NET classes (including the ZipArchive in System.IO.Compression) do.

**Comment by Numpsy** [comment]
Fixed by #302 ?

**Comment by Numpsy** [comment]
Think this one can be closed now?

**Comment by piksel** [comment]
Indeed!
