### ISSUE TITLE
When the first bit of the CRC is 0, 0 is not acquired, only 7 bits.

### ISSUE THREAD

**Issue by 99kyuu** [icsharpcode/SharpZipLib#230]
### Steps to reproduce
When the first bit of the CRC is 0, 0 is not acquired, only 7 bits.
```
....
  while ((theEntry = s.GetNextEntry()) != null) {
                if (fileName.Equals(theEntry.Name)) {
                    
                    string crcInfo = **theEntry.Crc.**ToString("X");
...
```

### Expected behavior
I do not know

### Actual behavior
When getting CRC

### Version of SharpZipLib
0.86.0.518

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [x] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by piksel** [comment]
I think your issue is about formatting the CRC of a zip file entry to a string, correct?
You expect it to output 8 hex characters, but if the CRC is lower than 268435456 (decimal) the `.ToString("X")` call will only output 7 characters.
In that case you can just use `.ToString("X8")` and it will add padding 0's to the beginning of the string, so
`268435456.ToString("X8")` outputs `0FFFFFFF`

**Comment by 99kyuu** [comment]
Thank you very much for your answer. The original formatting will have this problem.@piksel
