### ISSUE TITLE
ICSharpCode.SharpZipLib.Zip.ZipException: Wrong Central Directory signature

### ISSUE THREAD

**Issue by DmitriyKirakosyan** [icsharpcode/SharpZipLib#356]
File to test: https://dl.google.com/android/repository/sys-img/android-wear/x86-P_r02.zip.
SharpZipLib fails to unzip this file, while Windows10 is able to do it using `Extract All...` menu item.

### Steps to reproduce
1. Download the test file;
2. Try to unzip it using SharpZipLib;
3. Observe the `Wrong Central Directory signature` error.

### Version of SharpZipLib
1.1.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Confirmed. This is due to the fact that the file has a Zip64 Central Directory, while not using any Zip64 extensions. It also contains a non-zip64 CD, but it seems to be corrupt.  
  
The way SharpZipLib detects whether to use Zip64 is if any of the fields are set to all 1s (0xffff etc), and only then tries to find the Zip64 signature.  
This means that  `unzip` and other programs that just tries to find both headers at once works fine, while SharpZipLib (albeit correctly) complains about the invalid Central Directory.  
  
We should probably attempt to find the Zip64 signature at once as well, this would my the library work more like most other zip-implementations and handle non-compliant zip files better.

**Comment by piksel** [comment]
I made a new issue #357 for the root cause to link this and other issues into.
