### ISSUE TITLE
ZipAESTransform uses ECB.

### ISSUE THREAD

**Issue by tdhintz** [icsharpcode/SharpZipLib#367]
AES ECB mode at line 80 is no longer considered secure.  Is there a more secure solution?

**Comment by piksel** [comment]
Well, the thing is that ECB by itself is not secure, but what WinZip AES encryption uses is CTR.  
But since `System.Security.Cryptography` doesn't support CTR mode we have to implement it by hand. So the only reason we select ECB mode here is so that we can build our own mode on top of it, if that makes sense.  

Although even if CTR would be considered insecure, we couldn't just replace it with something else. The encryption is part of the standard, and doing something else would mean that we wouldn't be able to read files created by any other library (and no other library would be able to read our files).

**Comment by tdhintz** [comment]
Thank you,
