### ISSUE TITLE
why can't i get the correct entry size

### ISSUE THREAD

**Issue by wy6399542** [icsharpcode/SharpZipLib#456]
### Steps to reproduce
1.uploaded my HttpPostedFile
2.Read the .dat file in the zip file
3.return "Length not available for the current entry"

### Expected behavior
Read the .dat file and return correct string value

### Actual behavior
zipInput.Length throws the Exception 

### Version of SharpZipLib
0.86.0.518
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

here is my code:
```cs
string fileString = null;
ZipInputStream zipInput = new ZipInputStream(file.InputStream);
ZipEntry entry = null;
while ((entry = zipInput.GetNextEntry()) != null)
{
	if (entry.Name.EndsWith(fileExtName))
	{
		//entry.Size = inflaterInputBuffer.ReadLeInt();
		byte[] filebyte = new byte[zipInput.Length];
		zipInput.Read(filebyte, 0, filebyte.Length);
		string fileValue = Encoding.UTF8.GetString(filebyte);

		fileString = fileValue;
	}
}
zipInput.Close();
return fileString;
```
Thanks and Wait for helping

**Comment by Numpsy** [comment]
That sounds like the entry that you're reading has its length stored in a descriptor rather than in the file header, the effect of which is that ZipInputStream can't determine the length of the entry without reading all of the data for it.

If the entry is compressed, then it should still be able to read all of the data for the entry, but you won't be able to get the length up front, it's a matter of calling Read until it doesn't return more data.

**Comment by piksel** [comment]
The easiest way to do this is by using a `StreamReader` instance to handle the reads:
```cs
string fileString = null;
using var zipInput = new ZipInputStream(file.InputStream);
while (zipInput.GetNextEntry() is {} entry)
{
	if (entry.Name.EndsWith(fileExtName))
	{
                var streamReader= new StreamReader(zipInput, Encoding.UTF8);
		fileString = streamReader.ReadToEnd();
	}
}
return fileString;
```
Closing this as it seems resolved.
