### ISSUE TITLE
Getting offset / length

### ISSUE THREAD

**Issue by martinweihrauch** [icsharpcode/SharpZipLib#462]
Maybe this is offtopic here, but I have a question /feature request:

While writing the zip file and adding zip entries, is it - after having added a zip entry - possible to get the exact file offset + file length of the compressed or uncompressed file that was just written? 
So, I would need the offset of the file, not of the zip header for that file.
We are using it for a library, which later directly retrieves files by offset/length.

**Comment by Numpsy** [comment]
Using ZipFile or ZipOutputStream?

I think the compressed and uncompressed sizes should have been updated in the ZipEntries after they've been written, but i'm not sure if there is an exposed means of getting the offset of the file content rather than the header (if it isn't exposed directly it might be possible to calculate it from the other fields such as header offset and field sizes, but would have to look a bit more to see)

**Comment by piksel** [comment]
This is what `ZipFile` uses to calculate the data offset for an entry:
```cs
offsetOfFirstEntry + entry.Offset + ZipConstants.LocalHeaderBaseSize + extraLength
```
So if you check the base streams position before adding the entry, it should be possible to get the offset:
```cs
var offset = positionBefore + ZipConstants.LocalHeaderBaseSize + zipEntry.ExtraData.Length;
var uncompressed = zipEntry.Size;
var compressed = zipEntry.CompressedSize;
```
But there are a lot of if's here for sure. ZipFile/OutputStream and seekable vs non-seekable base streams.
