### ISSUE TITLE
How can I calculate the unzip progress?

### ISSUE THREAD

**Issue by jerry-zeng** [icsharpcode/SharpZipLib#464]
I want to display the unzip progress, but I can't get the total size or the number of entry in the zip, all I can do is like this:

// 1. scan all entries in the first loop
using ( var inputStream = new ZipInputStream(fileInfo.OpenRead()) )
{
    ZipEntry zipEntry;
    while ((zipEntry = inputStream.GetNextEntry()) != null)
    {
        // count the number or sum the size of entry
    }
}

// 2. loop again as above to unzip all entries, and calculate the progress percent

But, I think it's inefficiency, and will cause many memory garbage when doing "inputStream.GetNextEntry()"

Is there any better way to calculate the unzip progress?

**Comment by Numpsy** [comment]
The way ZipInputStream works (reading forward through the input stream reading entries as it goes) means that it can't know how many entries there are until it's read them all.

If you want to know how many entries there are in advance and have the whole file available up front then using ZipFile instead of ZipInputStream might be a better idea as it can tell you that info after opening the file.

**Comment by jerry-zeng** [comment]
thx, I will try it
