### ISSUE TITLE
Extract zip from MemoryStream?

### ISSUE THREAD

**Issue by qtghost** [icsharpcode/SharpZipLib#485]

**Comment by piksel** [comment]
Just to clarify what went wrong before; you wrote the output buffer (`MemoryStream`) to an array before closing the `ZipOutputStream`. The problem is that after all the file entries in the zipfile, there needs to be a sort of index of the contents of the file (the Central Directory mentioned in the error message). And since this comes after the file entries, it has to be written after all the entries has been added. Hence why it's done upon closing the `ZipOutputStream`. Hope that helps in clarifying what went wrong! Cheers.
