### ISSUE TITLE
Is there interest in supporting 7z or xz?

### ISSUE THREAD

**Issue by Rogardo** [icsharpcode/SharpZipLib#550]
Is there an interest to integrate the LZMA algorithm into the library? 
Would be really awesome so support this formats.

**Comment by Numpsy** [comment]
There was a previous question about that in #99 that didn't seem to go anywhere, not sure if any thought has gone into it beyond that.

**Comment by piksel** [comment]
If someone wants to give it a shot I'd be happy to assist, but at the moment there is no such ongoing effort.

**Comment by ds5678** [comment]
@piksel I'm interested in doing this. I have the C# portion of the 21.04 [7-Zip SDK](https://www.7-zip.org/sdk.html). What kinds of changes should I do to align it with the code standards here?

**Comment by piksel** [comment]
@ds5678 That depends on what your goal is. Reading .7z files requires a lot more work, since the SDK only contains the compression parts, not the archive parts (they're only in C and C++).
The easiest first step would probably be to implement ZipInput/OutputStream support for LZMA compression:
https://p1k.se/appnote.md#s58-lzma---method-14

**Comment by ds5678** [comment]
@piksel my primary goal is to have support for LZMA compression and decompression in zip files. 

However, reading and writing .7z files also appeals to me. Do you know whether I'd have to port just the C code or both it and the C++ code? I've done similar, albeit smaller, conversions to C# before.

**Comment by tinohager** [comment]
@ds5678 check this project https://github.com/adamhathcock/sharpcompress
