### ISSUE TITLE
SystemDefaultCodePage inconsistent

### ISSUE THREAD

**Issue by workgroupengineering** [icsharpcode/SharpZipLib#637]
### Steps to reproduce
1. Create simple program like this
   ``` csharp
   using ICSharpCode.SharpZipLib.Zip;
   using System;

   namespace TestZipCodePage
   {
      class Program
      {
        static void Main(string[] args)
        {
            Console.WriteLine($"SystemDefaultCodePage {ZipStrings.SystemDefaultCodePage}");

            Console.ReadKey();
        }
      }
   }
   ```
2. Set project target netcoreapp3.1
3. Run
4. Will be print `SystemDefaultCodePage 65001`
5. Change target to net48
6. Run
7. Will be print `SystemDefaultCodePage 1252`

### Expected behavior
- SystemDefaultCodePage consistent across all target platforms.
- ZipEntry Name encoded correctly when target is net48.

### Actual behavior
- if the target is netcoreapp3.1 SystemDefaultCodePage is **65001**
- if the target is net48 SystemDefaultCodePage **1552**
- ZipEntry Name not encoded correctly when target is net48.

### Obtained from (only keep the relevant lines)
Tried with:
- Compiled from source, commit: 8c0a16904a0fa545c198c2ebe56335974925d120
- Package installed using NuGet: **1.3.2**

**Comment by piksel** [comment]
This is the intended behaviour right now.

> ZipEntry Name not encoded correctly when target is net48.

What is "correctly"?
As per the zip standard, the encoding explicitly has to be Code Page 437 if EFS the general purpose bit flag is not set.
If it *is* set it should instad be UTF-8.
ref: [APPNOTE Appendix D](https://p1k.se/appnote.md#sappendix-d---language-encoding-efs)

The problem is that the majority of zip producers completely disregards this and uses the OS default encoding instead for non-unicode name encoding. This is what SharpZipLib mimics when no Unicode/EFS flag is set.

.NET Core doesn't support getting the OS active code page (as it's a windows-only concept), so `Encoding.Default` returns UTF-8 (`65001`) instead.
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=net-5.0#the-default-property-in-net-framework

If your use case is not just printing a string, but you have an actual problem that you want to solve,  please create a new discussion with your code.
