### ISSUE TITLE
ZipInputStream cannot read in-place updated archives

### ISSUE THREAD

**Issue by tangkq** [icsharpcode/SharpZipLib#639]
### Steps to reproduce
1.unity2018 empty project
2.build apk by Internal build system
3.unzip the apk
code:
```
ZipInputStream s = new ZipInputStream(File.OpenRead(file));	
ZipEntry theEntry;
while ((theEntry = s.GetNextEntry()) != null)
```
test apk file
[https://pan.baidu.com/s/1UJLdYwWMvpuoVjqCZaB-Hg](url)
net disk key: 5ygk

### Expected behavior
unzip the apk success

### Actual behavior
we get Incorrect and Garbled string and then Run to GetNextEntry while has some exception as "Wrong Local header signature: 0x50000000"

### Version of SharpZipLib
v1.3.2

### Obtained from (only keep the relevant lines)
source code from github

**Comment by piksel** [comment]
Could you upload the file somewhere else? Seems like you need some app to download the file:
![image](https://user-images.githubusercontent.com/807383/120781559-7871ff80-c529-11eb-8eba-a184ab5c8391.png)
You should be able to just attach it to the issue/comment directly in github.

**Comment by tangkq** [comment]
https://www.dropbox.com/s/k7ft4aq80fkzp88/test.apk?dl=0
here is the dropbox net disk link

**Comment by piksel** [comment]
Okay, this is the analysis of the file:
https://pub.p1k.se/sharpziplib/archivediag/test.apk.html
and this is the output from `infozip`:
https://pub.p1k.se/sharpziplib/archivediag/test.apk-zipinfo.txt

There is a lot of strange things going on in the file. My best guess is that either the last buffered write was never flushed to the file, or it was opened using `FileMode.Open` instead of `FileMode.Create` (which leaves data in the file if the amount written to it is less than the existing file).

**Comment by piksel** [comment]
Tried creating an empty project in `2019.4.15f1`, switched platform to android and built to an APK.
The resulting file does not show the same errors as your apk, but it does have the [Version needed to extract](https://p1k.se/appnote.md#s443-version-needed-to-extract-2-bytes) set to 0 for some files, which is not a valid value...
Not sure why it's doing that, but those should at least be extractable anyway.

Archive diag from my local project:
https://pub.p1k.se/sharpziplib/archivediag/local-test.apk.html

Zipinfo:
https://pub.p1k.se/sharpziplib/archivediag/local-test.apk-zipinfo.txt

**Comment by piksel** [comment]
Okay, I know what is going on now. The ZIP archive has been "in-place updated" and the remaining space between entries is filled with null bytes. 
Currently `ZipInputStream` cannot read such archives, but it is possible to support it with some modifications. I have implemented those into ArchiveDiag which now successfully iterates through the entries using `ZipInputStream.GetNextEntry()`:
https://pub.p1k.se/sharpziplib/archivediag/test.apk-v0.5.html

I will make a PR with these changes, but for now, use `ZipFile` instead of `ZipInputStream` as it uses the central headers and random access instead.

Example:
```cs
using var zipFile = new ZipFile(file);
foreach(var entry in zipFile) 
{
  var entryContentStream = zipFile.GetInputStream(entry);
  // ... 
}
```

**Comment by piksel** [comment]
I guess you found your solution. It's still an issue in the code, so I'd like to keep this open until #642 is merged.
