### ISSUE TITLE
Stream returned by ZipFile.GetInputStream(ZipEntry) is not seekable?

### ISSUE THREAD

**Issue by SpiritBob** [icsharpcode/SharpZipLib#650]
Can we please get an overload that allows returning a stream that is seekable?

This is because many libraries that read .xlsx files (which are zips) need the stream to support seeking, or else reading will fail.

Are there any alternatives I can do to get a seekable stream for a given `ZipEntry`?

Thank you.

**Comment by piksel** [comment]
You can copy the contents into a memory stream, or if you just want to seek forwards you can read N bytes into a buffer that you then discard. The reason for it not being seekable is because of how the deflate compression works. You cannot actually seek inside it (without doing either of the above things).
