### ISSUE TITLE
Code Scanning Alerts (CWE-327)

### ISSUE THREAD

**Issue by HowToDoThis** [icsharpcode/SharpZipLib#653]
Hi, I'm first time opening issues in here, just have a curious while code scanning this project.

### Steps to reproduce
1. Fork this project
2. Make a Github CodeQL CI (Via Security>Code Scanning Alert)
3. Make a random commit
4. CWE-327 reported by CI

### Version of SharpZipLib
git/master - source

### Obtained from (only keep the relevant lines)
- Compiled from source, commit: latest

### Messages
The occurs CWE-327 from this line
https://github.com/icsharpcode/SharpZipLib/blob/b10d4fbd9a465d017d4834640d64348e17683d45/src/ICSharpCode.SharpZipLib/Encryption/ZipAESTransform.cs#L82-L82
Should we fix it or change to another method or just ignore it?

**Comment by piksel** [comment]
Yeah, this is actually a false positive. Since Zip AES encryption uses a mode that is really uncommon (basically just in zip files), the .NET AES library doesn't support it. Instead, we use a basic mode (that is weak when used standalone) and implement the additional bits on top.
There might be an argument to be made about the resulting encryption's strength, but since it's defined in the (extended) spec, we cannot do much about it.

**Comment by HowToDoThis** [comment]
alright then, thanks for your response, I taught you guys didn't know it so I filed this problem.

**Comment by piksel** [comment]
Thanks! I also added CodeQL to the CI (f04d973a065fe3057f319b39d8ad03f16b2981bb) so that we can address similar issues (and more explicitly mark this as false positive).
