### ISSUE TITLE
-1 returned from ZipEntry.ExternalFileAttributes

### ISSUE THREAD

**Issue by emmayspark** [icsharpcode/SharpZipLib#734]
### Steps to reproduce
1. Zip a file on Linux using Info-Zip
2. Unzip using the library
3. Try to retrieve the file permissions 
 `int unixFilePermission = zipEntry.ExternalFileAttributes; `

### Expected behavior
unixFilePermission returns the right int value 

### Actual behavior
ExternalFileAttributes returns -1 for all extracted files (zip entry)

### Version of SharpZipLib 
1.3.3

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Could you provide the code you are using?
For `ZipFile` it always reads the two bytes from the central headers and assign them to the entry:
https://github.com/icsharpcode/SharpZipLib/blob/71fe846be1f405ab1d9833510ef6d24339bd77ac/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L3629
So that would mean that the actual value inside the file is actually `-1`, or perhaps there is something else going on with how you read them...

**Comment by emmayspark** [comment]
Thanks @piksel 

```
using (var zipInputStream = new ZipInputStream(zipFile))
 {
    while (zipInputStream.GetNextEntry() is ZipEntry zipEntry
       {
                  var entryFileName = zipEntry.Name;
                  int unixFilePermission = zipEntry.ExternalFileAttributes; // return -1 
        }
 }
````

Here is the code and zipEntry.ExternalFileAttributes alwasy returns -1.
So you are saying it's reading value from central headers, same value of each entry externalAttributes is expected?

What does it mean the value is -1? what permission does it stand for?

**Comment by emmayspark** [comment]
thanks @piksel, then this case there is no way I can read external file attributes? I'm looking at the code in GetNextEntry() and seems we might can add header and file data.?

**Comment by piksel** [comment]
> also I'm using zipInputStream not outputStream :)

haha, yeah, that was just a typo of mine. 

well, the ZipInputStream reads the zipfile as a stream, from the start to the end. the problem is that zipfiles contains one header just before the data for each entry, but also a "index" at the end of the archive. it's in this index that the external attributes are written, meaning that you would have to seek to the end the input to get to it. this would not be feasible for a streaming zip file, where random access might not be possible.

you could instead used `ZipFile` to read the archive, which uses the "index" at the end of the file:
```cs
using (var zipFile = new ZipFile(outStream))
{
    foreach (ZipEntry zipEntry in zipFile)
    {
        var entryFileName = zipEntry.Name;
        int unixFilePermission = zipEntry.ExternalFileAttributes;
    }
}
```

**Comment by emmayspark** [comment]
Thanks In my case, I'm trying to extract and parse data immediately without needing to wait for the ZIP file to buffer. because of the structure of zip archive, I believe zip permission cannot be retrieved in real-time. 

What about after I finished the downloading streaming and then access central directory to retrieve permission later on? Is it possible?

**Comment by piksel** [comment]
Not anything I tried, but the central directory is at the very end, so you could either make a custom stream wrapper that buffers the reads and permits seeking within the last BUFFER_SIZE bytes. That way you could just open the stream with `ZipFile` after the last entry has been read, iterate over the entries and just update the permissions.

I *think* that would work. Reading the data wouldn't work of course, but as long as you allow the seeks, the iteration of the entries should work...
